# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\layout_setup.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QObject
from PyQt5.QtCore import pyqtSignal
import math
from sympy import isprime


def recommend_row_col(index):
    if index > 2 and isprime(index):
        index += 1
    dictionary = {}
    for i in range(1, index + 1):
        if index % i == 0:
            dictionary[i + index // i] = [i, index // i]
    return dictionary[min(dictionary.keys())]


class Widget_Layout_Setup(QtWidgets.QWidget):
    sig_apply_layout = pyqtSignal(int, int)

    def __init__(self):
        super().__init__()
        self.rows = 0
        self.cols = 0
        self.setupUi()
        self.connect_signals()

    def connect_signals(self):
        self.txt_cameras_count.textChanged.connect(self.slot_cameras_count_changed)
        self.btn_apply.clicked.connect(self.slot_apply)
        self.btn_cancel.clicked.connect(self.hide)

    def slot_apply(self):
        if self.txt_cameras_count.text().isdigit() and self.rows and self.cols:
            if self.rows and self.cols:
                self.sig_apply_layout.emit(int(self.txt_rows.text()), int(self.txt_columns.text()))
            self.hide()
        else:
            QtWidgets.QMessageBox.warning(None, "Cảnh báo", "Kiểm tra lại giá trị nhập liệu")

    def slot_cameras_count_changed(self, text_):
        if text_.isdigit():
            cam_count = int(text_)
            if cam_count:
                self.rows, self.cols = recommend_row_col(cam_count)
                self.txt_rows.setText(str(self.rows))
                self.txt_columns.setText(str(self.cols))
        elif not text_:
            pass
        else:
            QtWidgets.QMessageBox.warning(None, "Cảnh báo", "Yêu cầu nhập số tự nhiên")

    def setupUi(self):
        self.setObjectName("Form")
        self.resize(271, 190)
        self.setStyleSheet("background-color: rgb(0, 85, 127);")
        self.gridLayout = QtWidgets.QGridLayout(self)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setStyleSheet("color: rgb(255, 255, 127);")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.txt_cameras_count = QtWidgets.QLineEdit(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_cameras_count.sizePolicy().hasHeightForWidth())
        self.txt_cameras_count.setSizePolicy(sizePolicy)
        self.txt_cameras_count.setStyleSheet("background-color: rgb(216, 216, 162);")
        self.txt_cameras_count.setObjectName("txt_cameras_count")
        self.gridLayout.addWidget(self.txt_cameras_count, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setStyleSheet("color: rgb(255, 255, 127);")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.txt_rows = QtWidgets.QLineEdit(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_rows.sizePolicy().hasHeightForWidth())
        self.txt_rows.setSizePolicy(sizePolicy)
        self.txt_rows.setStyleSheet("background-color: rgb(216, 216, 162);")
        self.txt_rows.setObjectName("txt_rows")
        self.gridLayout.addWidget(self.txt_rows, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setStyleSheet("color: rgb(255, 255, 127);")
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.txt_columns = QtWidgets.QLineEdit(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_columns.sizePolicy().hasHeightForWidth())
        self.txt_columns.setSizePolicy(sizePolicy)
        self.txt_columns.setStyleSheet("background-color: rgb(216, 216, 162);")
        self.txt_columns.setObjectName("txt_columns")
        self.gridLayout.addWidget(self.txt_columns, 2, 1, 1, 1)
        self.btn_apply = QtWidgets.QPushButton(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_apply.sizePolicy().hasHeightForWidth())
        self.btn_apply.setSizePolicy(sizePolicy)
        self.btn_apply.setStyleSheet("background-color: rgb(170, 170, 0);")
        self.btn_apply.setObjectName("btn_apply")
        self.gridLayout.addWidget(self.btn_apply, 3, 0, 1, 1)
        self.btn_cancel = QtWidgets.QPushButton(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_cancel.sizePolicy().hasHeightForWidth())
        self.btn_cancel.setSizePolicy(sizePolicy)
        self.btn_cancel.setStyleSheet("background-color: rgb(170, 170, 0);")
        self.btn_cancel.setObjectName("btn_cancel")
        self.gridLayout.addWidget(self.btn_cancel, 3, 1, 1, 1)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Số lượng camera"))
        self.label_2.setText(_translate("Form", "Số dòng"))
        self.label_3.setText(_translate("Form", "Số cột"))
        self.btn_apply.setText(_translate("Form", "Chấp nhận"))
        self.btn_cancel.setText(_translate("Form", "Hủy bỏ"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    ui = Widget_Layout_Setup()
    ui.show()
    sys.exit(app.exec_())
