# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI\widget_search.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1017, 751)
        Form.setStyleSheet("background-color: rgb(0, 63, 93);")
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.image = QtWidgets.QGroupBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.image.sizePolicy().hasHeightForWidth())
        self.image.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.image.setFont(font)
        self.image.setStyleSheet("color: rgb(190,190,0)")
        self.image.setAlignment(QtCore.Qt.AlignCenter)
        self.image.setFlat(False)
        self.image.setCheckable(False)
        self.image.setObjectName("image")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.image)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.qlabel_img_plate = QtWidgets.QLabel(self.image)
        self.qlabel_img_plate.setMinimumSize(QtCore.QSize(0, 50))
        self.qlabel_img_plate.setStyleSheet("background: silver")
        self.qlabel_img_plate.setText("")
        self.qlabel_img_plate.setObjectName("qlabel_img_plate")
        self.gridLayout_3.addWidget(self.qlabel_img_plate, 0, 0, 1, 1)
        self.qlabel_image = QtWidgets.QLabel(self.image)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qlabel_image.sizePolicy().hasHeightForWidth())
        self.qlabel_image.setSizePolicy(sizePolicy)
        self.qlabel_image.setStyleSheet("background: black")
        self.qlabel_image.setText("")
        self.qlabel_image.setObjectName("qlabel_image")
        self.gridLayout_3.addWidget(self.qlabel_image, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.image, 0, 1, 1, 1)
        self.video = QtWidgets.QGroupBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.video.sizePolicy().hasHeightForWidth())
        self.video.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.video.setFont(font)
        self.video.setStyleSheet("color: rgb(190,190,0)")
        self.video.setAlignment(QtCore.Qt.AlignCenter)
        self.video.setObjectName("video")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.video)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.qlabel_video_plate = QtWidgets.QLabel(self.video)
        self.qlabel_video_plate.setMinimumSize(QtCore.QSize(0, 50))
        self.qlabel_video_plate.setStyleSheet("background: silver")
        self.qlabel_video_plate.setText("")
        self.qlabel_video_plate.setAlignment(QtCore.Qt.AlignCenter)
        self.qlabel_video_plate.setObjectName("qlabel_video_plate")
        self.gridLayout_4.addWidget(self.qlabel_video_plate, 0, 0, 1, 1)
        self.qlabel_video = QtWidgets.QLabel(self.video)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qlabel_video.sizePolicy().hasHeightForWidth())
        self.qlabel_video.setSizePolicy(sizePolicy)
        self.qlabel_video.setStyleSheet("background: black")
        self.qlabel_video.setText("")
        self.qlabel_video.setObjectName("qlabel_video")
        self.gridLayout_4.addWidget(self.qlabel_video, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.video, 1, 1, 1, 1)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setStyleSheet("background-color: rgb(0, 71, 104);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btn_search = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_search.sizePolicy().hasHeightForWidth())
        self.btn_search.setSizePolicy(sizePolicy)
        self.btn_search.setMinimumSize(QtCore.QSize(0, 30))
        self.btn_search.setStyleSheet("QPushButton{\n"
"    background-color: rgb(250, 250, 0);\n"
"    border: none;\n"
"    border-radius: 10px\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(109, 109, 0);\n"
"    border: none;\n"
"    border-radius: 10px\n"
"}")
        self.btn_search.setObjectName("btn_search")
        self.gridLayout_2.addWidget(self.btn_search, 0, 2, 1, 1)
        self.qlabel_text_plate = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.qlabel_text_plate.setFont(font)
        self.qlabel_text_plate.setStyleSheet("color: rgb(170, 170, 0);")
        self.qlabel_text_plate.setObjectName("qlabel_text_plate")
        self.gridLayout_2.addWidget(self.qlabel_text_plate, 0, 0, 1, 1)
        self.txt_search_plate = QtWidgets.QTextEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_search_plate.sizePolicy().hasHeightForWidth())
        self.txt_search_plate.setSizePolicy(sizePolicy)
        self.txt_search_plate.setMinimumSize(QtCore.QSize(0, 30))
        self.txt_search_plate.setMaximumSize(QtCore.QSize(16777215, 30))
        self.txt_search_plate.setStyleSheet("background-color:rgb(250, 250, 0);")
        self.txt_search_plate.setObjectName("txt_search_plate")
        self.gridLayout_2.addWidget(self.txt_search_plate, 0, 1, 1, 1)
        self.qtable_list_vehicle = QtWidgets.QTableWidget(self.frame)
        self.qtable_list_vehicle.setObjectName("qtable_list_vehicle")
        self.qtable_list_vehicle.setColumnCount(0)
        self.qtable_list_vehicle.setRowCount(0)
        self.gridLayout_2.addWidget(self.qtable_list_vehicle, 1, 0, 1, 3)
        self.gridLayout.addWidget(self.frame, 0, 0, 2, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.image.setTitle(_translate("Form", "Hình ảnh"))
        self.video.setTitle(_translate("Form", "Video"))
        self.btn_search.setText(_translate("Form", "Tìm kiếm"))
        self.qlabel_text_plate.setText(_translate("Form", "Biển số"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
